# Project information
site_name: Denis Markushin's blog
site_url: https://denis-markushin.github.io
site_author: Denis Markushin
site_description: >-
  Thoughts and Musings on the world of Programming and beyond

# Repository
repo_name: denis-markushin/denis-markushin.github.io
repo_url: https://github.com/denis-markushin/denis-markushin.github.io

# Copyright
copyright: Copyright &copy; 2024&ndash;2026 Denis Markushin

# Configuration
theme:
  custom_dir: overrides
  name: material
  features:
    - content.code.copy
    - content.code.annotate
    - content.tooltips
    - navigation.indexes
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - navigation.path
    - navigation.footer
    - navigation.sections
    - toc.follow
    - search.highlight
    - search.share
    - search.suggest
  icon:
    logo: material/code-tags
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: Inter
    code: JetBrains Mono

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/denis-markushin
      name: GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/denis-markushin
      name: LinkedIn

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: '#'
  - admonition
  - pymdownx.details

# Plugins
plugins:
  - blog:
      blog_dir: '.'
      archive: true
      categories: true
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - tags
  - rss:
      match_path: "/posts/.*"
      date_from_meta:
        as_creation: date.created
        as_update: date.updated
  - glightbox

remote_branch: gh-pages

strict: true